//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellRecharges.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process
    {
        public int Id { get; set; }
        public double Cost { get; set; }
        public string CellPhoneNumber { get; set; }
        public string Type { get; set; }
        public System.DateTime Date { get; set; }

       
    }
}
