USE [master]
GO

/****** Object:  Database [CellRecharges]    Script Date: 18/07/2017 17:01:37 ******/
CREATE DATABASE [CellRecharges]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CellRecharges', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\CellRecharges.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CellRecharges_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\CellRecharges_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CellRecharges] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CellRecharges].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CellRecharges] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CellRecharges] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CellRecharges] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CellRecharges] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CellRecharges] SET ARITHABORT OFF 
GO

ALTER DATABASE [CellRecharges] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CellRecharges] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [CellRecharges] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CellRecharges] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CellRecharges] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CellRecharges] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CellRecharges] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CellRecharges] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CellRecharges] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CellRecharges] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CellRecharges] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CellRecharges] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CellRecharges] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CellRecharges] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CellRecharges] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CellRecharges] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CellRecharges] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CellRecharges] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CellRecharges] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CellRecharges] SET  MULTI_USER 
GO

ALTER DATABASE [CellRecharges] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CellRecharges] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CellRecharges] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CellRecharges] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CellRecharges] SET  READ_WRITE 
GO


